# Generated by Django 3.2.16 on 2023-11-17 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='created_ad',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='created_ad',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_ad',
            new_name='created_at',
        ),
    ]
